#!/bin/sh

# Create a conda environment named opennmt if it doesnt exist
conda_env_name="opennmt"
if conda env list | grep -q $conda_env_name; then
    echo "Conda environment exists"
else
    echo "Conda environment does not exist"
    echo "Creating conda environment..."
    echo "Creating conda environment..."
    conda create -n $conda_env_name python=3.8
fi

eval "$(conda shell.bash hook)"
conda deactivate
conda activate $conda_env_name
# install cuda 11.8 with conda
pip install -e . # Install OpenNMT-py in the conda environment
pip3 install  -r requirements.txt # Update some of the packages to versions that work well with OpenNMT-py 1.2.0

echo "---"
echo "Done."
echo "Please run 'conda activate $conda_env_name' to activate the Conda environment before running any scripts."
echo "---"